"use strict";

let albums =
[
    new Album ({
        name: "Seventh Star",
        artist: "Black Sabbath",
        genre: "Heavy Metal",
        releaseYear: 1986,
        cover: "covers/black-sabbath--seventh-star.png",
        spotifyLink: "https://open.spotify.com/album/557z9zU5A2g5jhZBiu8obi",
    }),
    new Album ({
        name: "The Very Best",
        artist: "INXS",
        genre: "New Wave",
        releaseYear: 2011,
        cover: "covers/inxs--the-very-best.png",
        spotifyLink: "https://open.spotify.com/album/0ByciEsG5VvGzWOG7o3rAn",
    }),
    new Album ({
        name: "No Easy Way Out",
        artist: "Robert Tepper",
        genre: "Rock",
        releaseYear: 1986,
        cover: "covers/robert-tepper--no-easy-way-out.png",
        spotifyLink: "https://open.spotify.com/album/1hN5Xzuzfhqk2sIBtNZmP1",
    }),
    new Album ({
        name: "Fixed",
        artist: "Nine Inch Nails",
        genre: "Industrial Rock",
        releaseYear: 1992,
        cover: "covers/nine-inch-nails--fixed.png",
        spotifyLink: "https://open.spotify.com/album/6tmbCwAFWR5Qe9TaXjP8jN",
    }),
    new Album ({
        name: "Don't Stop",
        artist: "Billy Idol",
        genre: "Dance-Rock",
        releaseYear: 1981,
        cover: "covers/billy-idol--dont-stop.png",
        spotifyLink: "https://open.spotify.com/album/6UNswjupuKnxiPMnEAa9Hp",
    }),
    new Album ({
        name: "Dreams of Reason Produce Monsters",
        artist: "Mick Karn",
        genre: "Experimental Rock",
        releaseYear: 1986,
        cover: "covers/mick-karn--dreams-of-reason-produce-monsters.png",
        spotifyLink: "https://open.spotify.com/album/6dZ3jcyq6IIEdEpOS1rsDM",
    }),
    new Album ({
        name: "Songs for the Deaf",
        artist: "Queens of the Stone Age",
        genre: "Stoner Rock",
        releaseYear: 2002,
        cover: "covers/queens-of-the-stone-age--songs-for-the-deaf.png",
        spotifyLink: "https://open.spotify.com/album/4w3NeXtywU398NYW4903rY",
    }),
    new Album ({
        name: "Don't Say No",
        artist: "Billy Squier",
        genre: "Rock",
        releaseYear: 1981,
        cover: "covers/billy-squier--dont-say-no.png",
        spotifyLink: "https://open.spotify.com/album/6TwlLNU5Zd9qGuNgSLeWPt",
    }),
    new Album ({
        name: "16 Strokes: The Best of Billy Squier",
        artist: "Billy Squier",
        genre: "Rock",
        releaseYear: 1995,
        cover: "covers/billy-squier--16-strokes-the-best-of-billy-squier.png",
        spotifyLink: "https://open.spotify.com/album/6YtnoMLw5v2UhFTReAn7z1",
    }),
    new Album ({
        name: "Damn Yankees",
        artist: "Damn Yankees",
        genre: "Hard Rock",
        releaseYear: 1990,
        cover: "covers/damn-yankees--damn-yankees.png",
        spotifyLink: "https://open.spotify.com/album/2GSZ2kruaBmA5hR9xngeBX",
    }),
    new Album ({
        name: "Mr. Big",
        artist: "Mr. Big",
        genre: "Hard Rock",
        releaseYear: 1989,
        cover: "covers/mr-big--mr-big.png",
        spotifyLink: "https://open.spotify.com/album/18HPDet34B8LwgCfagDeZd",
    }),
    new Album ({
        name: "Lean into It",
        artist: "Mr. Big",
        genre: "Hard Rock",
        releaseYear: 1991,
        cover: "covers/mr-big--lean-into-it.png",
        spotifyLink: "https://open.spotify.com/album/6CrjpyjlfjK95oHF6dvEnQ",
    }),
    new Album ({
        name: "In Trance",
        artist: "Scorpions",
        genre: "Hard Rock",
        releaseYear: 1975,
        cover: "covers/scorpions--in-trance.png",
        spotifyLink: "https://open.spotify.com/album/1IxCkGzmfbrod37MqDPUHm",
    }),
    new Album ({
        name: "Lest We Forget (The Best Of)",
        artist: "Marilyn Manson",
        genre: "Heavy Metal",
        releaseYear: 2004,
        cover: "covers/marilyn-manson--lest-we-forget-the-best-of.png",
        spotifyLink: "https://open.spotify.com/album/16iYefmYfh5RJg4XEi6rG9",
    }),
    new Album ({
        name: "Further Down the Spiral",
        artist: "Nine Inch Nails",
        genre: "Post-industrial",
        releaseYear: 1995,
        cover: "covers/nine-inch-nails--further-down-the-spiral.png",
        spotifyLink: "https://open.spotify.com/album/6v4pXGNQv0Xc81H3iYdybc",
    }),
    new Album ({
        name: "The Headless Children",
        artist: "W.A.S.P",
        genre: "Heavy Metal",
        releaseYear: 1989,
        cover: "covers/wasp--the-headless-children.png",
        spotifyLink: "https://open.spotify.com/album/73tznjCvNu9tDQW5jcrglq",
    }),
    new Album ({
        name: "The Crimson Idol",
        artist: "W.A.S.P",
        genre: "Heavy Metal",
        releaseYear: 1992,
        cover: "covers/wasp--the-crimson-idol.png",
        spotifyLink: "https://open.spotify.com/album/1qIXNs2KIv1DfO01lwoUfz",
    }),
    new Album ({
        name: "2112",
        artist: "Rush",
        genre: "Progressive Rock",
        releaseYear: 1976,
        cover: "covers/rush--2112.png",
        spotifyLink: "https://open.spotify.com/album/5g5aKkI0ExfU4kDvADP6JK",
    }),
    new Album ({
        name: "Seven Inches of Satanic Panic",
        artist: "Ghost",
        genre: "Psychedelic Rock",
        releaseYear: 2019,
        cover: "covers/ghost--seven-inches-of-satanic-panic.png",
        spotifyLink: "https://open.spotify.com/album/6eOWfFjfBPRsAW0ZS4sbaF",
    }),
    new Album ({
        name: "Point Blank",
        artist: "Nailbomb",
        genre: "Industrial Thrash Metal",
        releaseYear: 1994,
        cover: "covers/nailbomb--point-blank.png",
        spotifyLink: "https://open.spotify.com/album/0CcgwAkqiglrLu6lH5lrSU",
    }),
    new Album ({
        name: "Catch the Fall",
        artist: "The Dolphin Brothers",
        genre: "New Wave",
        releaseYear: 1987,
        cover: "covers/the-dolphin-brothers--catch-the-fall.png",
        spotifyLink: "https://open.spotify.com/album/2bwRV1MkfbD4rEcNNQjGRA",
    }),
    new Album ({
        name: "No Heavy Petting",
        artist: "UFO",
        genre: "Hard Rock",
        releaseYear: 1976,
        cover: "covers/ufo--no-heavy-petting.png",
        spotifyLink: "https://open.spotify.com/album/3lu8Z9INHhbKLpS4LkJArz",
    }),
    new Album ({
        name: "Straight Between the Eyes",
        artist: "Rainbow",
        genre: "Hard Rock",
        releaseYear: 1982,
        cover: "covers/rainbow--straight-between-the-eyes.png",
        spotifyLink: "https://open.spotify.com/playlist/0QFpnE6PHJyczy8mQYVQdk",
    }),
    new Album ({
        name: "Seed",
        artist: "JBK",
        genre: "Alternative",
        releaseYear: 1994,
        cover: "covers/jbk--seed.png",
        spotifyLink: "https://jbkmusic.bandcamp.com/album/seed",
    }),
    new Album ({
        name: "Generation Terrorists",
        artist: "Manic Street Preachers",
        genre: "Alternative Rock",
        releaseYear: 1992,
        cover: "covers/manic-street-preachers--generation-terrorists.png",
        spotifyLink: "https://open.spotify.com/album/5ZhZUAD6C0CkjXPsuDggmA",
    }),
];