"use strict";

let albums2020 =
{
    year: 2020,
    content: 
    [
        new Album ({
            name: "Homework",
            artist: "Daft Punk",
            genre: "House",
            releaseYear: 1997,
            cover: "covers/daft-punk--homework.png",
            streamLink: "https://open.spotify.com/album/5uRdvUR7xCnHmUW8n64n9y",
        }),
        new Album ({
            name: "Discovery",
            artist: "Daft Punk",
            genre: "Disco",
            releaseYear: 2001,
            cover: "covers/daft-punk--discovery.png",
            streamLink: "https://open.spotify.com/album/2noRn2Aes5aoNVsU6iWThc",
        }),
        new Album ({
            name: "Human After All",
            artist: "Daft Punk",
            genre: "Dance-rock",
            releaseYear: 2005,
            cover: "covers/daft-punk--human-after-all.png",
            streamLink: "https://open.spotify.com/album/2T7DdrOvsqOqU9bGTkjBYu",
        }),
        new Album ({
            name: "Random Access Memories",
            artist: "Daft Punk",
            genre: "Disco",
            releaseYear: 2013,
            cover: "covers/daft-punk--random-access-memories.png",
            streamLink: "https://open.spotify.com/album/4m2880jivSbbyEGAKfITCa",
        }),
        new Album ({
            name: "Mob Rules",
            artist: "Black Sabbath",
            genre: "Heavy Metal",
            releaseYear: 1981,
            cover: "covers/black-sabbath--mob-rules.png",
            streamLink: "https://open.spotify.com/album/2iaECLD2YLSEOkSfi7BRaC",
        }),
        new Album ({
            name: "Holy Diver",
            artist: "Dio",
            genre: "Heavy Metal",
            releaseYear: 1983,
            cover: "covers/dio--holy-diver.png",
            streamLink: "https://open.spotify.com/album/1QJmLRcuIMMjZ49elafR3K",
        }),
        new Album ({
            name: "Live at The Brixton Academy",
            artist: "Faith No More",
            genre: "Alternative Metal",
            releaseYear: 1991,
            cover: "covers/faith-no-more--live-at-the-brixton-academy.png",
            streamLink: "https://open.spotify.com/album/30aiwTsoJlbCIDXqDT947h",
        }),
        new Album ({
            name: "Bad",
            artist: "Michael Jackson",
            genre: "Pop",
            releaseYear: 1987,
            cover: "covers/michael-jackson--bad.png",
            streamLink: "https://open.spotify.com/album/3Us57CjssWnHjTUIXBuIeH",
        }),
        new Album ({
            name: "Dangerous",
            artist: "Michael Jackson",
            genre: "New Jack Swing",
            releaseYear: 1991,
            cover: "covers/michael-jackson--dangerous.png",
            streamLink: "https://open.spotify.com/album/0oX4SealMgNXrvRDhqqOKg",
        }),
        new Album ({
            name: "Scary Monsters (and Super Creeps)",
            artist: "David Bowie",
            genre: "Art Rock",
            releaseYear: 1980,
            cover: "covers/david-bowie--scary-monsters-and-super-creeps.png",
            streamLink: "https://open.spotify.com/album/5fxvWHvIDPIALfTfRiwyB0",
        }),
        new Album ({
            name: "Lament",
            artist: "Ultravox",
            genre: "New Wave",
            releaseYear: 1984,
            cover: "covers/ultravox--lament.png",
            streamLink: "https://open.spotify.com/album/4gwKE70npgEOk9sFd9aTYt",
        }),
        new Album ({
            name: "Burn",
            artist: "Deep Purple",
            genre: "Hard Rock",
            releaseYear: 1974,
            cover: "covers/deep-purple--burn.png",
            streamLink: "https://open.spotify.com/album/3wR7UC2ij2dx0TbtiMP4J9",
        }),
        new Album ({
            name: "Star Fleet Project",
            artist: "Brian May",
            genre: "Hard Rock",
            releaseYear: 1983,
            cover: "covers/brian-may--star-fleet-project.png",
            streamLink: "https://www.youtube.com/watch?v=Zux1-a2rRHc",
        }),
        new Album ({
            name: "David Bowie (1969)",
            artist: "David Bowie",
            genre: "Folk Rock",
            releaseYear: 1969,
            cover: "covers/david-bowie--david-bowie.png",
            streamLink: "https://open.spotify.com/album/1ay9Z4R5ZYI2TY7WiDhNYQ",
        }),
        new Album ({
            name: "The Album",
            artist: "Haddaway",
            genre: "Eurodance",
            releaseYear: 1993,
            cover: "covers/haddaway--the-album.png",
            streamLink: "https://open.spotify.com/album/1LAx7yCVbGwskdnGDof8SC",
        }),
        new Album ({
            name: "Scoundrel Days",
            artist: "A-ha",
            genre: "Synth-pop",
            releaseYear: 1986,
            cover: "covers/a-ha--scoundrel-days.png",
            streamLink: "https://open.spotify.com/album/0Or3lqjBWQAfmyigntPSL6",
        }),
        new Album ({
            name: "The Top",
            artist: "The Cure",
            genre: "Gothic Rock",
            releaseYear: 1984,
            cover: "covers/the-cure--the-top.png",
            streamLink: "https://open.spotify.com/album/5OniNO040dM4H5kAlet3XV",
        }),
        new Album ({
            name: "Ordinary Man",
            artist: "Ozzy Osbourne",
            genre: "Heavy Metal",
            releaseYear: 2020,
            cover: "covers/ozzy-osbourne--ordinary-man.png",
            streamLink: "https://open.spotify.com/album/2x2cG56QicVfymWnRF0Nmj",
        }),
        new Album ({
            name: "Badmotorfinger",
            artist: "Soundgarden",
            genre: "Grunge",
            releaseYear: 1991,
            cover: "covers/soundgarden--badmotorfinger.png",
            streamLink: "https://open.spotify.com/album/2W6MaUiInBkna5DfBES4E3",
        }),
        new Album ({
            name: "White Feathers",
            artist: "Kajagoogoo",
            genre: "New Wave",
            releaseYear: 1983,
            cover: "covers/kajagoogoo--white-feathers.png",
            streamLink: "https://open.spotify.com/album/52koatNHePHRWEmmkP0z2Z",
        }),
        new Album ({
            name: "How Could It Be",
            artist: "Eddie Murphy",
            genre: "R&B",
            releaseYear: 1985,
            cover: "covers/eddie-murphy--how-could-it-be.png",
            streamLink: "https://open.spotify.com/album/2ghvihRomDb37X59VK6hp5",
        }),
        new Album ({
            name: "Disconnected",
            artist: "Dry Cell",
            genre: "Nu Metal",
            releaseYear: 2002,
            cover: "covers/dry-cell--disconnected.png",
            streamLink: "https://open.spotify.com/playlist/4UOYLanHctM74mBt1pcdUQ",
        }),
        new Album ({
            name: "Iron Savior",
            artist: "Iron Savior",
            genre: "Power Metal",
            releaseYear: 1997,
            cover: "covers/iron-savior--iron-savior.png",
            streamLink: "https://open.spotify.com/album/2DfiAmdJotkHGxKVgCJgtk",
        }),
        new Album ({
            name: "Give Me Fire",
            artist: "Mando Diao",
            genre: "Indie rock",
            releaseYear: 2009,
            cover: "covers/mando-diao--give-me-fire.png",
            streamLink: "https://open.spotify.com/album/0Z6I8nXSQ5QPfuCPcoXlMj",
        }),
    ]
}