"use strict";

const albums =
[
    new Album ({
        name: "Seventh Star",
        artist: "Black Sabbath",
        genre: "Heavy Metal",
        releaseYear: 1986,
        cover: "https://upload.wikimedia.org/wikipedia/en/2/25/Black-Sabbath-seventh-star.jpg",
        spotifyLink: "https://open.spotify.com/album/557z9zU5A2g5jhZBiu8obi",
    }),
    new Album ({
        name: "The Very Best",
        artist: "INXS",
        genre: "New Wave",
        releaseYear: 2011,
        cover: "https://upload.wikimedia.org/wikipedia/en/2/2b/INXS_-_The_Very_Best.png",
        spotifyLink: "https://open.spotify.com/album/0ByciEsG5VvGzWOG7o3rAn",
    }),
    new Album ({
        name: "No Easy Way Out",
        artist: "Robert Tepper",
        genre: "Rock",
        releaseYear: 1986,
        cover: "https://upload.wikimedia.org/wikipedia/en/a/aa/Robert_Tepper_No_Easy_Way_Out_1986_Album_Cover.jpg",
        spotifyLink: "https://open.spotify.com/album/1hN5Xzuzfhqk2sIBtNZmP1",
    }),
    new Album ({
        name: "Fixed",
        artist: "Nine Inch Nails",
        genre: "Industrial Rock",
        releaseYear: 1992,
        cover: "https://upload.wikimedia.org/wikipedia/en/f/f0/Nine_Inch_Nails_-_Fixed.png",
        spotifyLink: "https://open.spotify.com/album/6tmbCwAFWR5Qe9TaXjP8jN",
    }),
    new Album ({
        name: "Don't Stop",
        artist: "Billy Idol",
        genre: "Dance-Rock",
        releaseYear: 1981,
        cover: "https://upload.wikimedia.org/wikipedia/en/1/1d/BillyIdolDontStop.jpg",
        spotifyLink: "https://open.spotify.com/album/6UNswjupuKnxiPMnEAa9Hp",
    }),
    new Album ({
        name: "Dreams of Reason Produce Monsters",
        artist: "Mick Karn",
        genre: "Experimental Rock",
        releaseYear: 1986,
        cover: "https://rovimusic.rovicorp.com/image.jpg?c=TtCUvUxs95KSLNd16Zz-PZhUoDg0hsvx4F4sL4oO-nA=&f=5",
        spotifyLink: "https://open.spotify.com/album/6dZ3jcyq6IIEdEpOS1rsDM",
    }),
    new Album ({
        name: "Songs for the Deaf",
        artist: "Queens of the Stone Age",
        genre: "Stoner Rock",
        releaseYear: 2002,
        cover: "https://upload.wikimedia.org/wikipedia/en/0/01/Queens_of_the_Stone_Age_-_Songs_for_the_Deaf.png",
        spotifyLink: "https://open.spotify.com/album/4w3NeXtywU398NYW4903rY",
    }),
    new Album ({
        name: "Don't Say No",
        artist: "Billy Squier",
        genre: "Rock",
        releaseYear: 1981,
        cover: "https://upload.wikimedia.org/wikipedia/en/8/83/Billy_Squier_-_Don%27t_Say_No.jpg",
        spotifyLink: "https://open.spotify.com/album/6TwlLNU5Zd9qGuNgSLeWPt",
    }),
    new Album ({
        name: "16 Strokes: The Best of Billy Squier",
        artist: "Billy Squier",
        genre: "Rock",
        releaseYear: 1995,
        cover: "https://rovimusic.rovicorp.com/image.jpg?c=0T6qDMFp68tgb6jrEZEzPA4Q1ghY8VaPylnm7PwcKNY=&f=5",
        spotifyLink: "https://open.spotify.com/album/6YtnoMLw5v2UhFTReAn7z1",
    }),
    new Album ({
        name: "Damn Yankees",
        artist: "Damn Yankees",
        genre: "Hard Rock",
        releaseYear: 1990,
        cover: "https://upload.wikimedia.org/wikipedia/en/b/b1/DYDY.jpg",
        spotifyLink: "https://open.spotify.com/album/2GSZ2kruaBmA5hR9xngeBX",
    }),
    new Album ({
        name: "Mr. Big",
        artist: "Mr. Big",
        genre: "Hard Rock",
        releaseYear: 1989,
        cover: "https://upload.wikimedia.org/wikipedia/en/f/f0/Mr_Big_Self-Titled.jpg",
        spotifyLink: "https://open.spotify.com/album/18HPDet34B8LwgCfagDeZd",
    }),
    new Album ({
        name: "Lean into It",
        artist: "Mr. Big",
        genre: "Hard Rock",
        releaseYear: 1991,
        cover: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Mr._Big_-_Lean_Into_It.jpg",
        spotifyLink: "https://open.spotify.com/album/6CrjpyjlfjK95oHF6dvEnQ",
    }),
    new Album ({
        name: "In Trance",
        artist: "Scorpions",
        genre: "Hard Rock",
        releaseYear: 1975,
        cover: "https://upload.wikimedia.org/wikipedia/en/f/fc/In_Trance_%28Scorpions_album_-_cover_art%29.jpg",
        spotifyLink: "https://open.spotify.com/album/1IxCkGzmfbrod37MqDPUHm",
    }),
    new Album ({
        name: "Lest We Forget (The Best Of)",
        artist: "Marilyn Manson",
        genre: "Heavy Metal",
        releaseYear: 2004,
        cover: "https://upload.wikimedia.org/wikipedia/en/0/06/Marilyn_Manson_-_Lest_We_Forget.png",
        spotifyLink: "https://open.spotify.com/album/16iYefmYfh5RJg4XEi6rG9",
    }),
    new Album ({
        name: "Further Down the Spiral",
        artist: "Nine Inch Nails",
        genre: "Post-industrial",
        releaseYear: 1995,
        cover: "https://upload.wikimedia.org/wikipedia/en/1/17/Further_down_the_spiral.jpg",
        spotifyLink: "https://open.spotify.com/album/6v4pXGNQv0Xc81H3iYdybc",
    }),
    new Album ({
        name: "The Headless Children",
        artist: "W.A.S.P",
        genre: "Heavy Metal",
        releaseYear: 1989,
        cover: "https://upload.wikimedia.org/wikipedia/en/d/db/The_Headless_Children_%28W.A.S.P._album_-_cover_art%29.jpg",
        spotifyLink: "https://open.spotify.com/album/73tznjCvNu9tDQW5jcrglq",
    }),
    new Album ({
        name: "The Crimson Idol",
        artist: "W.A.S.P",
        genre: "Heavy Metal",
        releaseYear: 1992,
        cover: "https://upload.wikimedia.org/wikipedia/en/7/75/Waspcrimsonidol.jpg",
        spotifyLink: "https://open.spotify.com/album/1qIXNs2KIv1DfO01lwoUfz",
    }),
    new Album ({
        name: "2112",
        artist: "Rush",
        genre: "Progressive Rock",
        releaseYear: 1976,
        cover: "https://upload.wikimedia.org/wikipedia/en/c/c9/Rush_2112.jpg",
        spotifyLink: "https://open.spotify.com/album/5g5aKkI0ExfU4kDvADP6JK",
    }),

];